blank_issues_enabled: true
contact_links:
  - name: Ask a Question
    url: 'https://t.me/romankurnovskii'
    about: 'Question or Collaboration'
  - name: Roman Kurnovskii
    url: https://romankurnovskii.com
    about: web