blank_issues_enabled: true
contact_links:
  - name: telegram
    url: 'https://t.me/romankurnovskii'
    about: 'Question or Collaboration'
  - name: web
    url: https://romankurnovskii.com
    about: link